version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev  # <-- recomendado para dev
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - /app/node_modules  # Evita sobrescrever node_modules local do container
    working_dir: /app
    command: npm run dev
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_dev
    ports:
      - "5432:5432"  # útil para conectar pelo seu host (ex: DBeaver)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data: